version: '3'
services:
  wog:
    image: ye8323/worldofgames:latest
    restart: always
    build: .
    container_name: worldofgames_world_of_games
    ports:
      - "8777:8777"
    volumes:
      - .:/WorldOfGames
